#!/usr/bin/env bash

BASEDIR=$(pwd)
echo $BASEDIR
DIR=$(echo $BASEDIR | cut -d'/' -f7-)
echo $DIR
rm -Rf ../../poadio/$DIR/src
cp -Rvf src ../../poadio/$DIR
cd ../../poadio/$DIR
git add --all
git commit -m "update"
git push origin main
cd ../../$DIR
